version: '1.0.0'
services:
  MQTT_broker:
    image: emqx/nanomq:0.21
    ports:
      - 1883:1883 
      - 8083:8083 
      - 8883:8883
    networks:
        main:
            aliases:
                - nanomq
  web-frontend:
    build: ./
    restart: always
    environment:
      - NUXT_ADMIN_USERNAME=admin
      - NUXT_ADMIN_PASSWORD=admin123
      - NUXT_DOCKER_INGEST_URI=http://nginx
      - INGEST_SERVER=49.228.131.109:3359
    networks:
        main:
            aliases:
                - web
  nginx-http-flv:
    build: ./nginx
    restart: always
    ports:
      - '80:80/tcp'
      - '443:443/tcp'
      - '1935:1935/tcp'
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf:ro
      - ./nginx/logs:/usr/local/nginx/logs
    networks:
        main:
            aliases:
                - nginx
    depends_on:
        - web-frontend
networks:
    main: